### ISSUE TITLE
Hi, where is the code?

### ISSUE THREAD

**Issue by plsuarez** [heitorrapela/MiPa#1]

**Comment by heitorrapela** [comment]
Hi @plsuarez, thanks for your interest in our work! 

We were waiting for the peer review process. Now that the paper has been accepted at WACV2025, we will focus on finishing the camera ready, cleaning, and releasing the code.

**Comment by heitorrapela** [comment]
Hello @plsuarez, sorry for the delay. 

We released the first version of the code. I will close this issue. 

Next, we will provide more details on installation/data prep and runs; thanks for your patience. 

Best Regards, Heitor Medeiros
